name: Deploy

on:
  push:
    branchs: ["master"]
    
  workflow_dispatch:
    
permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      
      - name: Install .NET Wasm Tools
        run: dotnet workload install wasm-tools
        
      - name: Restore Dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c Release --no-restore
        
      - name: Publish .NET
        run: dotnet publish Estudos.Projeto.Teste/Estudos.Projeto.Teste.csproj -c:Release -o docs --nologo
        
      - name: Create 404 for SPA routing
        run: |
          echo '<!DOCTYPE html>
          <html>
          <head>
              <meta http-equiv="refresh" content="0; url=./index.html" />
          </head>
          <body>
              <script>
                  var path = window.location.pathname + window.location.search + window.location.hash;
                  
                  var repoName = "/Estudos.Projeto.Teste";
                  
                  if (path.startsWith(repoName)) {
                    path = path.substring(repoName.length);
                }
        
                  window.location.href = repoName + "/index.html#" + path;
              </script>
          </body>
          </html>' > docs/wwwroot/404.html
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/wwwroot'
        
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4